source 'http://rubygems.org'

gem 'jekyll-paginate'
gem 'jekyll-sitemap', :git => 'https://github.com/jekyll/jekyll-sitemap.git'
gem 'nokogiri'
gem 'fastimage'
gem 'redcarpet'
gem 'pygments.rb'
gem 'amp-jekyll'
gem 'jekyll-seo-tag'
